### ISSUE TITLE
Harvester doesn't seem to be working properly.

### ISSUE THREAD

**Issue by TheQuadShot** [K-4U/Hydraulicraft#124]
The harvester leaves blank spots in the field
![2015-06-05_12 53 10](https://cloud.githubusercontent.com/assets/11265900/8013993/d440a496-0b81-11e5-9027-88be34ca7f0e.png)

**Comment by TheQuadShot** [comment]
if I harvest some wheat b4 the harvester (the arm wasn't moving until after I harvested), it will harvest the seeds/seedling

**Comment by TheQuadShot** [comment]
There is inconsistent behavior with shift right clicking the harvester inventory. If I shift click say wheat, it moves around with in the inventory on the left (I haven't ever seen anything on the right), but if I have wheat in my inventory, it will sometimes "top off" what I have, to a full stack. I can't shift click into the harvester inventory  .

**Comment by K-4U** [comment]
With regards to seeds not being planted, this really has to do with light levels. When you'd try to plant a normal seed there, they also shouldn't plant, i could be wrong, but testing in my world seemed to make it work: 
![screenshot 2015-07-14 17 14 27](https://cloud.githubusercontent.com/assets/76641/8676791/cf8904be-2a4b-11e5-8025-e6044380a80f.png)

With regards to the shift-clicking. This is already fixed in the current (beta) release.

**Comment by TheQuadShot** [comment]
Sorry, I should have put the light level in report, we did discuss this on IRC, So I put 2 GalactiCraft arc lamps on each side, they produce the highest light level I know of (light level 15).
